[database]
name=nutriscope
categories=en:groceries, en:beverages, en:snacks, en:biscuits, en:cheeses, en:confectioneries

[db_columns]
# IDENTIFICATION
code
product_name
brands_tags
image_url
image_small_url
image_ingredients_url
image_ingredients_small_url
image_nutrition_url
image_nutrition_small_url
# CLASSIFICATION
main_category
categories_tags
food_groups
# NUTRITION
energy_100g
fat_100g
saturated-fat_100g
sugars_100g
fiber_100g
proteins_100g
salt_100g
fruits-vegetables-legumes_100g
# ADDITIFS
additives_tags
# SCORES OFFICIELS
nutriscore_score
nutriscore_grade
nova_group
environmental_score_grade
# FILTRAGE & EXPÉRIENCE UTILISATEUR
ingredients_text
allergens
traces
countries
quantity
labels_tags
# INDICATEUR DE QUALITÉ
nutriscore_data_complete